name: huntly_container
services:
  db:
    image: postgres:17-alpine
    container_name: huntly
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=huntly_pass
      - POSTGRES_DB=huntly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: